[workspace]
members = [
  "core",
  "memberlist",
  "transports/net",
  "transports/quic",
  "utils",
  # "js",
  # "nodejs",
  # "py",
]
exclude = ["memberlist-wasm"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "Apache-2.0/MIT"
repository = "https://github.com/al8n/memberlist"
homepage = "https://github.com/al8n/memberlist"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.dependencies]
auto_impl = "1"
agnostic = "0.2"
async-channel = "2"
bytes = "1.5"
byteorder = "1"
derive_more = "0.99"
futures = "0.3"
metrics = "0.22"
nodecraft = { version = "0.2", features = [
  "transformable",
  "async",
  "resolver",
  "agnostic",
] }
paste = "1"
pin-project = "1"
scopeguard = "1"
serde = { version = "1", features = ["derive", "rc"] }
humantime-serde = "1"
smallvec = "1"
smol_str = "0.2"
transformable = "0.1.6"
thiserror = "1"
tracing = "0.1"
viewit = "0.1.5"
wg = { version = "0.4", features = ["async"] }

memberlist-core = { path = "core", default-features = false }
memberlist-net = { path = "transports/net", default-features = false }
memberlist-quinn = { path = "transports/quinn", default-features = false }
memberlist-s2n = { path = "transports/s2n", default-features = false }
memberlist-utils = { path = "utils", default-features = false }
