[workspace]
members = [
  "core",
  "showbiz",
  "transport",
  "traits",
  "types"
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "Apache-2.0/MIT"
repository = "https://github.com/al8n/showbiz"
homepage = "https://github.com/al8n/showbiz"

[workspace.dependencies]
bytes = "1.4"
either = "1.8"
local-ip-address = "0.5"
viewit = "0.1.5"
scopeguard = "1"
socket2 = "0.5"
tracing = "0.1"
