[workspace]
members = [
  "core",
  "memberlist",
  "types",
  "transports/net",
  "transports/quic",
  # "bindings/js",
  # "bindings/nodejs",
  # "bindings/py",
]
resolver = "2"

[workspace.package]
version = "0.2.0-alpha.3"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/al8n/memberlist"
homepage = "https://github.com/al8n/memberlist"
readme = "README.md"
rust-version = "1.75.0"
keywords = ["swim", "gossip", "service-discovery"]
categories = ["network-programming", "asynchronous"]

[workspace.package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.dependencies]
auto_impl = "1"
atomic_refcell = "0.1"
agnostic-lite = { version = "0.3", features = ["time"] }
agnostic = "0.3.5"
async-lock = "3"
async-channel = "2"
bytes = "1.5"
byteorder = "1"
derive_more = "0.99"
futures = "0.3"
indexmap = "2"
local-ip-address = "0.6"
metrics = "0.22"
nodecraft = { version = "0.3", features = [
  "transformable",
  "async",
  "resolver",
  "agnostic",
] }
paste = "1"
pin-project = "1"
scopeguard = "1"
serde = { version = "1", features = ["derive", "rc"] }
humantime-serde = "1"
smallvec = "1"
smallvec-wrapper = { version = "0.1", features = ["const_new", "either"] }
smol_str = "0.2"
transformable = { version = "0.1.6", features = ["smol_str", "bytes"] }
thiserror = "1"
tracing = "0.1"
viewit = "0.1.5"

memberlist-core = { version = "0.2.0-alpha.1", path = "core", default-features = false }
memberlist-net = { version = "0.2.0-alpha.1", path = "transports/net", default-features = false }
memberlist-types = { version = "0.2.0-alpha.1", path = "types", default-features = false }
memberlist-quic = { version = "0.2.0-alpha.1", path = "transports/quic", default-features = false }
