rust_input: [src/options.rs]
dart_output: [lib/lib/bridge_generated.dart]
wasm: true
dart_decl_output: lib/lib/bridge_definitions.dart
dart_format_line_length: 120
dart_enums_style: true
c_output: [c_output_path/c_output.h]
extra_c_output_path:
  - c_output_path_extra/
# dump: []