/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_options_free(a: number): void;
export function options_name(a: number, b: number): void;
export function options_label(a: number, b: number): void;
export function options_skip_inbound_label_check(a: number): number;
export function options_bind_addr(a: number, b: number): void;
export function options_advertise_addr(a: number, b: number): void;
export function options_protocol_version(a: number): number;
export function options_tcp_timeout(a: number): number;
export function options_indirect_checks(a: number): number;
export function options_retransmit_mult(a: number): number;
export function options_suspicion_mult(a: number): number;
export function options_suspicion_max_timeout_mult(a: number): number;
export function options_push_pull_interval(a: number): number;
export function options_probe_interval(a: number): number;
export function options_probe_timeout(a: number): number;
export function options_disable_tcp_pings(a: number): number;
export function options_awareness_max_multiplier(a: number): number;
export function options_gossip_interval(a: number): number;
export function options_gossip_nodes(a: number): number;
export function options_gossip_to_the_dead_time(a: number): number;
export function options_gossip_verify_incoming(a: number): number;
export function options_gossip_verify_outgoing(a: number): number;
export function options_enable_compression(a: number): number;
export function options_secret_key(a: number, b: number): void;
export function options_delegate_protocol_version(a: number): number;
export function options_delegate_protocol_min(a: number): number;
export function options_delegate_protocol_max(a: number): number;
export function options_dns_config_path(a: number, b: number): void;
export function options_handoff_queue_depth(a: number): number;
export function options_packet_buffer_size(a: number): number;
export function options_dead_node_reclaim_time(a: number): number;
export function options_require_node_names(a: number): number;
export function options_cidrs_allowed(a: number): number;
export function options_queue_check_interval(a: number): number;
export function options_with_name(a: number, b: number, c: number): number;
export function options_with_label(a: number, b: number, c: number): number;
export function options_with_skip_inbound_label_check(a: number, b: number): number;
export function options_with_bind_addr(a: number, b: number, c: number): number;
export function options_with_advertise_addr(a: number, b: number, c: number): number;
export function options_with_protocol_version(a: number, b: number): number;
export function options_with_tcp_timeout(a: number, b: number): number;
export function options_with_indirect_checks(a: number, b: number): number;
export function options_with_retransmit_mult(a: number, b: number): number;
export function options_with_suspicion_mult(a: number, b: number): number;
export function options_with_suspicion_max_timeout_mult(a: number, b: number): number;
export function options_with_push_pull_interval(a: number, b: number): number;
export function options_with_probe_interval(a: number, b: number): number;
export function options_with_probe_timeout(a: number, b: number): number;
export function options_with_disable_tcp_pings(a: number, b: number): number;
export function options_with_awareness_max_multiplier(a: number, b: number): number;
export function options_with_gossip_interval(a: number, b: number): number;
export function options_with_gossip_nodes(a: number, b: number): number;
export function options_with_gossip_to_the_dead_time(a: number, b: number): number;
export function options_with_gossip_verify_incoming(a: number, b: number): number;
export function options_with_gossip_verify_outgoing(a: number, b: number): number;
export function options_with_enable_compression(a: number, b: number): number;
export function options_with_secret_key(a: number, b: number, c: number): number;
export function options_with_delegate_protocol_version(a: number, b: number): number;
export function options_with_delegate_protocol_min(a: number, b: number): number;
export function options_with_delegate_protocol_max(a: number, b: number): number;
export function options_with_dns_config_path(a: number, b: number, c: number): number;
export function options_with_handoff_queue_depth(a: number, b: number): number;
export function options_with_packet_buffer_size(a: number, b: number): number;
export function options_with_dead_node_reclaim_time(a: number, b: number): number;
export function options_with_require_node_names(a: number, b: number): number;
export function options_add_allowed_cidr(a: number, b: number, c: number): number;
export function options_clear_allowed_cidrs(a: number): number;
export function options_with_queue_check_interval(a: number, b: number): number;
export function options_lan(): number;
export function options_wan(): number;
export function options_local(): number;
export function __wbg_duration_free(a: number): void;
export function duration_zero(): number;
export function duration_millisecond(): number;
export function duration_second(): number;
export function duration_minute(): number;
export function duration_hour(): number;
export function duration_day(): number;
export function duration_week(): number;
export function duration_from_millis(a: number): number;
export function duration_from_secs(a: number): number;
export function duration_as_millis(a: number): number;
export function duration_as_secs(a: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
