[package]
name = "quinn"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agnostic = { workspace = true, features = ["quinn"] }
quinn = { version = "0.10.2", default-features = false, features = ["tls-rustls", "futures-io"] }
thiserror.workspace = true
smol_str.workspace = true
socket2 = "0.5"
rustls = { version = "0.21.9", default-features = false }