[package]
name = "showbiz-types"
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
version = { workspace= true }
edition = { workspace= true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true, features = ["serde"] }
prost = "0.11"
viewit = { workspace = true }
smol_str = { version = "0.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }


[dev-dependencies]
serde_json = "1"