[package]
name = "memberlist"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "A placeholder"

[features]
default = []

[dependencies]
