[package]
name = "showbiz-core"
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
version = { workspace= true }
edition = { workspace= true }

[features]
default = ["metrics"]

# TODO: temporarily disable nightly, wait Rust's issue https://github.com/rust-lang/rust/issues/111105 to be fixed
# nightly = ["agnostic/nightly"]

# implement tokio::io::AsyncRead/AsyncWrite for Tcp/Udp
tokio-compat = ["agnostic/tokio-compat"]
metrics = ["dep:metrics"]

# expose all tests fn for users who want to use other runtime
# see showbiz-wasm for more examples about how to use those tests fn
test = ["tracing-subscriber"]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
trust-dns-resolver = { version = "0.23.0-alpha.4", default-features = false, features = ["system-config"] }

[target.'cfg(target_family = "wasm")'.dependencies]
trust-dns-resolver = { version = "0.23.0-alpha.4", default-features = false }
resolv-conf = { version = "0.7", default-features = false }
getrandom = { version = "0.2", features = ["js"] }
once_cell = "1.17"

[target.'cfg(not(any(target_family = "wasm", windows)))'.dependencies]
rustix = { version = "0.38", features = ["system"] }

[target.'cfg(windows)'.dependencies]
hostname = "0.3"

[dependencies]
# async common
agnostic = { workspace = true, features = ["net"] }
async-channel = { version = "1.8" }
async-lock = { version = "2.7" }
async-recursion = { version = "1" }
async-trait = { version = "0.1" }
futures-channel = { version = "0.3" }
futures-util = { version = "0.3", features = ["io"] }

# common
atomic = "=0.5" # keep on 0.5
aead = { version = "0.5", features = ["bytes"] }
aes-gcm = "0.10"
bytes = { workspace = true, features = ["serde"] }
base64 = "0.21"
bytemuck = { version = "1.3", features = ["derive"] }
cbc = "0.1"
crc32fast = "1"
crossbeam-utils = "0.8"
crossbeam-skiplist = "0.1"
crossbeam-queue = "0.3"
either = "1"
local-ip-address = "0.5"
itertools = "0.11"
ipnet = { version = "2.7", features = ["serde"] }
metrics = { version = "0.21", optional = true }
paste = "1" # TODO: remove this dependency when Rust's concat_ident macro stable
parking_lot = { version = "0.12", features = ["send_guard"] }
pollster = "0.3"
rand = { version = "0.8" }
rayon = "1.7"
rkyv = { git = "https://github.com/rkyv/rkyv.git", rev = "bf39dbc3a61783774fc7e1d47b8bf75db2581be7", features = ["validation", "bytes"] }
scopeguard = "1.1"
serde = { workspace = true }
humantime-serde = "1"
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", optional = true, features = ["env-filter", "tracing-log"] }
trust-dns-proto = { version = "0.23", default-features = false }
viewit = { workspace = true }
weezl = { version = "0.1", features = ["async"] }
wg = "0.3"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter", "tracing-log"] }
prost = "0.11"
agnostic = { path = "../../agnostic/agnostic", features = ["tokio-net", "async-std-net", "smol-net"] }
tokio = { version = "1.32", features = ["full"] }
tokio-util = { version = "0.7", features = ["compat"] }
