[package]
name = "showbiz-core"
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
version = { workspace= true }
edition = { workspace= true }

[features]
default = []

sync = ["crossbeam-channel"]
async = ["async-channel", "async-trait", "futures"]


[dependencies]

# sync
crossbeam-channel = { version = "0.5", optional = true }

# async common
async-trait = { version = "0.1", optional = true }
async-channel = { version = "1.8", optional = true }
futures = { version = "0.3", optional = true }

# common
bytes = { workspace = true, features = ["serde"] }
crossbeam-utils = "0.8"
either = { workspace = true }
local-ip-address = { workspace = true }
metrics = "0.20"
parking_lot = "0.12"
showbiz-types = { path = "../types" }
showbiz-traits = { path = "../traits" }
scopeguard = { workspace = true }
serde = { version = "1", features = ["derive"] }
socket2 = { workspace = true }
thiserror = "1"
tracing = { workspace = true }
viewit = { workspace = true }
wg = "0.3"
