// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.75.2.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class ShowbizDartPlatform extends FlutterRustBridgeBase<ShowbizDartWire> with FlutterRustBridgeSetupMixin {
  ShowbizDartPlatform(FutureOr<WasmModule> dylib) : super(ShowbizDartWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

// Section: finalizer
}

// Section: WASM wire module

@JS('wasm_bindgen')
external ShowbizDartWasmModule get wasmModule;

@JS()
@anonymous
class ShowbizDartWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external ShowbizDartWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_lan__static_method__Options(NativePortType port_);

  external dynamic /* void */ wire_wan__static_method__Options(NativePortType port_);

  external dynamic /* void */ wire_local__static_method__Options(NativePortType port_);
}

// Section: WASM wire connector

class ShowbizDartWire extends FlutterRustBridgeWasmWireBase<ShowbizDartWasmModule> {
  ShowbizDartWire(FutureOr<WasmModule> module) : super(WasmModule.cast<ShowbizDartWasmModule>(module));

  void wire_lan__static_method__Options(NativePortType port_) => wasmModule.wire_lan__static_method__Options(port_);

  void wire_wan__static_method__Options(NativePortType port_) => wasmModule.wire_wan__static_method__Options(port_);

  void wire_local__static_method__Options(NativePortType port_) => wasmModule.wire_local__static_method__Options(port_);
}
