//! Buffa-generated owned + view types for the inner wire messages.
//!
//! The types in this module are generated at build time from
//! `proto/memberlist/v1/messages.proto` via `buffa-build` + `buffa-codegen`.
//! Do not edit this file; edit the `.proto` schema instead.
//!
//! # Generated types
//!
//! - [`Alive`] / [`Suspect`] / [`Dead`] — membership change messages
//! - [`Ping`] / [`IndirectPing`] / [`Ack`] / [`Nack`] — probe messages
//! - [`PushPull`] / [`UserData`] / [`ErrorResponse`] — state-sync + misc
//! - [`Node`] / [`PushNodeState`] / [`State`] — supporting structures
//!
//! All `bytes` fields use [`bytes::Bytes`] (configured via
//! `buffa_build::Config::use_bytes_type()`).

#![allow(missing_docs)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/memberlist_wire_generated.rs"));

#[cfg(test)]
mod tests {
  use super::memberlist::v1::{Alive, Node};
  use buffa::Message as _;

  #[test]
  fn alive_roundtrip() {
    let original = Alive {
      incarnation: Some(42),
      meta: bytes::Bytes::new(),
      node: Some(Node {
        id: Some(bytes::Bytes::from_static(b"node-a")),
        addr: Some(bytes::Bytes::from_static(b"127.0.0.1:7000")),
        ..Default::default()
      })
      .into(),
      protocol_version: Some(1),
      delegate_version: Some(1),
      ..Default::default()
    };

    let encoded = original.encode_to_vec();
    let decoded = Alive::decode_from_slice(encoded.as_slice()).unwrap();

    assert_eq!(original.incarnation, decoded.incarnation);
    assert_eq!(original.protocol_version, decoded.protocol_version);
    assert_eq!(original.delegate_version, decoded.delegate_version);
  }
}
