[package]
name = "showbiz"
version = "0.0.0"
edition = "2021"

[features]
default = ["metrics"]
metrics = ["showbiz-core/metrics"]

tokio = []

async-std = []

smol = []

[dependencies]
agnostic = { workspace = true }
showbiz-core = { workspace = true }
