[package]
name = "memberlist-net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
metadata.workspace = true

[features]
default = ["dns", "compression", "encryption"]

tls = ["dep:futures-rustls"]
native-tls = ["dep:async-native-tls", "dep:native-tls"]

compression = ["rayon", "weezl"]
encryption = ["rayon", "aead", "aes-gcm", "cbc"]

serde = ["memberlist-core/serde", "dep:serde", "memberlist-utils/serde", "base64"]
rkyv = ["memberlist-core/rkyv"]

metrics = ["memberlist-core/metrics", "dep:metrics", "memberlist-utils/metrics"]
test = ["memberlist-core/test"]

# enable DNS node address resolver
dns = ["nodecraft/dns"]
dns-over-quic = ["dns", "nodecraft/dns-over-quic"]
dns-over-h3 = ["dns", "nodecraft/dns-over-h3"]
dns-over-https-rustls = ["dns", "nodecraft/dns-over-https-rustls"]
dns-over-rustls = ["dns", "nodecraft/dns-over-rustls"]
dns-over-openssl = ["dns", "nodecraft/dns-over-openssl"]
dns-over-native-tls = ["dns", "nodecraft/dns-over-native-tls"]
dns-webpki-roots = ["dns", "nodecraft/dns-webpki-roots"]
dns-native-certs = ["dns", "nodecraft/dns-native-certs"]
dnssec-openssl = ["dns", "nodecraft/dnssec-openssl"]
dnssec-ring = ["dns", "nodecraft/dnssec-ring"]
dnssec = ["dns", "nodecraft/dnssec"]

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dependencies]
agnostic.workspace = true
async-channel.workspace = true
async-lock = "3"
bytes.workspace = true
byteorder.workspace = true
crc32fast = "1"
either = "1"
futures.workspace = true
indexmap = "2"
local-ip-address = "0.5"
nodecraft = { workspace = true, features = ["async", "resolver", "agnostic"] }
pollster = "0.3"
peekable = { version = "0.2", features = ["future"] }
pin-project.workspace = true
rand = "0.8"

scopeguard.workspace = true
memberlist-core.workspace = true
memberlist-utils = { workspace = true, features = ["ipnet"] }
thiserror.workspace = true
tracing.workspace = true
viewit.workspace = true
wg = { version = "0.4", features = ["async"] }

# tls
futures-rustls = { version = "0.25", optional = true }

# native-tls
async-native-tls = { version = "0.5", optional = true }
native-tls = { version = "0.2", optional = true }

# compression & encryption
aead = { version = "0.5", features = ["bytes", "std"], optional = true }
aes-gcm = { version = "0.10", optional = true }
base64 = { version = "0.21", optional = true }
cbc = { version = "0.1", optional = true }
rayon = { version = "1.8", optional = true }
weezl = { version = "0.1", optional = true }

pnet = { version = "0.34", optional = true }
serde = { working = true, optional = true }
metrics = { workspace = true, optional = true }
