[package]
name = "showbiz-net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
metadata.workspace = true

[features]

compression = ["rayon", "weezl"]
encryption = ["rayon"]

serde = ["showbiz-core/serde", "dep:serde", "showbiz-utils/serde"]
rkyv = ["showbiz-core/rkyv"]

metrics = ["showbiz-core/metrics", "dep:metrics", "showbiz-utils/metrics"]
test = ["showbiz-core/test"]

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dependencies]
agnostic.workspace = true
async-channel.workspace = true
async-lock = "3"
bytes.workspace = true
byteorder.workspace = true
crc32fast = "1"
either = "1"
futures.workspace = true
indexmap = "2"
local-ip-address = "0.5"
nodecraft.workspace = true
pollster = "0.3"
rand = "0.8"

scopeguard.workspace = true
showbiz-core.workspace = true
showbiz-utils = { workspace = true, features = ["ipnet"] }
thiserror.workspace = true
tracing.workspace = true
viewit.workspace = true
wg = { version = "0.4", features = ["async"] }

# compression & encryption
aead = { version = "0.5", features = ["bytes"], optional = true }
aes-gcm = { version = "0.10", optional = true }
base64 = { version = "0.21", optional = true }
cbc = { version = "0.1", optional = true }
rayon = { version = "1.8", optional = true }
weezl = { version = "0.1", features = ["async"], optional = true }

pnet = { version = "0.34", optional = true }
serde = { working = true, optional = true }
metrics = { workspace = true, optional = true }
