[package]
name = "showbiz-net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
metadata.workspace = true

[features]

serde = ["showbiz-core/serde", "dep:serde", "showbiz-utils/serde"]
rkyv = ["showbiz-core/rkyv"]

metrics = ["showbiz-core/metrics", "dep:metrics"]

test = ["showbiz-core/test"]

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dependencies]
atomic = "=0.5" # keep on 0.5
agnostic.workspace = true
async-channel.workspace = true
aead = { version = "0.5", features = ["bytes"] }
aes-gcm = "0.10"
base64 = "0.21"
bytemuck = { version = "1.3", features = ["derive"] }
bytes.workspace = true
cbc = "0.1"
crc32fast = "1"
crossbeam-utils = "0.8"
crossbeam-skiplist = "0.1"
futures.workspace = true
local-ip-address = "0.5"
nodecraft.workspace = true
pollster = "0.3"
rand = "0.8"
scopeguard.workspace = true
showbiz-core.workspace = true
showbiz-utils.workspace = true
thiserror.workspace = true
tracing.workspace = true
viewit.workspace = true
wg = { version = "0.4", features = ["async"] }
weezl = { version = "0.1", features = ["async"] }

pnet = { version = "0.34", optional = true }
serde = { working = true, optional = true }
metrics = { workspace = true, optional = true }
