//! Buffa-generated owned + view types for the inner wire messages.
//!
//! The types in this module are generated at build time from
//! `proto/memberlist/v1/messages.proto` via `buffa-build` + `buffa-codegen`.
//! Do not edit this file; edit the `.proto` schema instead.
//!
//! # Generated types
//!
//! - [`Alive`] / [`Suspect`] / [`Dead`] — membership change messages
//! - [`Ping`] / [`IndirectPing`] / [`Ack`] / [`Nack`] — probe messages
//! - [`PushPull`] / [`UserData`] / [`ErrorResponse`] — state-sync + misc
//! - [`Node`] / [`PushNodeState`] / [`State`] — supporting structures
//!
//! All `bytes` fields use [`bytes::Bytes`] (configured via
//! `buffa_build::Config::use_bytes_type()`).

#![allow(missing_docs)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/memberlist_wire_generated.rs"));

#[cfg(test)]
mod tests;
