[package]
name = "memberlist-quic"
version = "0.5.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
description = "memberlist's transport layer based on QUIC"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["compression", "quinn"]
compression = ["rayon", "weezl"]
# encryption feature enables nothing, because of quic is secure by default, this feature only for adapt to other transport layer
encryption = ["memberlist-core/encryption"]
quinn = ["agnostic/quinn", "dep:quinn", "agnostic/net", "rustls"]
s2n = ["s2n-quic", "s2n-quic-transport", "futures/bilock", "futures/unstable"]
serde = ["memberlist-core/serde", "dep:serde", "humantime-serde", "indexmap/serde"]
metrics = ["memberlist-core/metrics", "dep:metrics"]

tokio = ["agnostic/tokio"]
async-std = ["agnostic/async-std"]
smol = ["agnostic/smol"]

# enable DNS node address resolver
dns = ["nodecraft/dns", "agnostic/dns"]
dns-over-quic = ["dns", "nodecraft/dns-over-quic", "agnostic/dns-over-quic"]
dns-over-h3 = ["dns", "nodecraft/dns-over-h3", "agnostic/dns-over-h3"]
dns-over-https-rustls = ["dns", "nodecraft/dns-over-https-rustls", "agnostic/dns-over-https-rustls"]
dns-over-rustls = ["dns", "nodecraft/dns-over-rustls", "agnostic/dns-over-rustls"]
dns-over-openssl = ["dns", "nodecraft/dns-over-openssl", "agnostic/dns-over-openssl"]
dns-over-native-tls = ["dns", "nodecraft/dns-over-native-tls", "agnostic/dns-over-native-tls"]
dns-webpki-roots = ["dns", "nodecraft/dns-webpki-roots", "agnostic/dns-webpki-roots"]
dns-native-certs = ["dns", "nodecraft/dns-native-certs", "agnostic/dns-native-certs"]
dnssec-openssl = ["dns", "nodecraft/dnssec-openssl", "agnostic/dnssec-openssl"]
dnssec-ring = ["dns", "nodecraft/dnssec-ring", "agnostic/dnssec-ring"]
dnssec = ["dns", "nodecraft/dnssec", "agnostic/dnssec"]

# enable test feature
test = ["memberlist-core/test", "rcgen"]

[dependencies]
auto_impl.workspace = true
atomic_refcell.workspace = true
agnostic-lite.workspace = true
agnostic = { workspace = true, optional = true, features = ["net"] }
async-channel.workspace = true
bytes.workspace = true
byteorder.workspace = true
crossbeam-skiplist = "0.1"
futures.workspace = true
indexmap = "2"
getifs.workspace = true
memberlist-core.workspace = true
nodecraft = { workspace = true, features = ["async", "resolver", "agnostic"] }
pin-project.workspace = true
peekable = { version = "0.2", features = ["future"] }
tracing.workspace = true
thiserror.workspace = true
smol_str.workspace = true
scopeguard.workspace = true
viewit.workspace = true

# serde
serde = { workspace = true, optional = true }
humantime-serde = { workspace = true, optional = true }

# metrics
metrics = { workspace = true, optional = true }

# quinn
quinn = { version = "0.11", default-features = false, optional = true, features = ["futures-io", "rustls"] }
rustls = { version = "0.23", default-features = false, optional = true }

# test
rcgen = { version = "0.13", optional = true }

# s2n
s2n-quic = { version = "1.52", optional = true }
s2n-quic-transport = { version = "0.53", optional = true }

# compression
rayon = { version = "1.8", optional = true }
weezl = { version = "0.1", optional = true }

[dev-dependencies]
agnostic = { workspace = true, features = ["net"] }
memberlist-core = { workspace = true, features = ["test"] }
smol_str.workspace = true
tokio = { version = "1", features = ["full"] }
test-cert-gen = { version = "0.9" }
paste.workspace = true

[[test]]
name = "memberlist-quic"
path = "tests/main.rs"
required-features = ["test"]