[package]
name = "memberlist-quic"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = ["compression", "quinn"]
compression = ["rayon", "weezl"]
quinn = ["agnostic/quinn", "dep:quinn", "rustls", "socket2"]
s2n = ["s2n-quic", "s2n-quic-transport", "futures/bilock", "futures/unstable"]
serde = ["memberlist-core/serde", "dep:serde", "memberlist-utils/serde", "humantime-serde", "indexmap/serde"]
metrics = ["memberlist-core/metrics", "memberlist-utils/metrics", "dep:metrics"]

# enable DNS node address resolver
dns = ["nodecraft/dns"]
dns-over-quic = ["dns", "nodecraft/dns-over-quic"]
dns-over-h3 = ["dns", "nodecraft/dns-over-h3"]
dns-over-https-rustls = ["dns", "nodecraft/dns-over-https-rustls"]
dns-over-rustls = ["dns", "nodecraft/dns-over-rustls"]
dns-over-openssl = ["dns", "nodecraft/dns-over-openssl"]
dns-over-native-tls = ["dns", "nodecraft/dns-over-native-tls"]
dns-webpki-roots = ["dns", "nodecraft/dns-webpki-roots"]
dns-native-certs = ["dns", "nodecraft/dns-native-certs"]
dnssec-openssl = ["dns", "nodecraft/dnssec-openssl"]
dnssec-ring = ["dns", "nodecraft/dnssec-ring"]
dnssec = ["dns", "nodecraft/dnssec"]

# enable test feature
test = ["memberlist-core/test", "rustls?/dangerous_configuration", "rcgen"]

[dependencies]
auto_impl.workspace = true
agnostic.workspace = true
async-channel.workspace = true
bytes.workspace = true
byteorder.workspace = true
futures.workspace = true
indexmap = "2"
local-ip-address = "0.5"
memberlist-core.workspace = true
memberlist-utils = { workspace = true, features = ["ipnet"] }
nodecraft = { workspace = true, features = ["async", "resolver", "agnostic"] }
pin-project.workspace = true
peekable = { version = "0.2", features = ["future"] }
pollster = "0.3"
tracing.workspace = true
thiserror.workspace = true
smol_str.workspace = true
viewit.workspace = true

# serde
serde = { workspace = true, optional = true }
humantime-serde = { workspace = true, optional = true }

# metrics
metrics = { workspace = true, optional = true }

# quinn
quinn = { version = "0.10.2", default-features = false, optional = true, features = ["tls-rustls", "futures-io"] }
socket2 = { version = "0.5", optional = true }
rustls = { version = "0.21.9", default-features = false, optional = true }

# test
rcgen = { version = "0.12", optional = true }

# s2n
s2n-quic = { version = "1.32", optional = true }
s2n-quic-transport = { version = "0.32", optional = true}

# compression
rayon = { version = "1.8", optional = true }
weezl = { version = "0.1", optional = true }

[dev-dependencies]
agnostic = { workspace = true, features = ["async-std", "smol", "tokio", "net"] }
memberlist-core = { workspace = true, features = ["test"] }
smol_str.workspace = true
tokio = { version = "1", features = ["full"] }
test-cert-gen = { version = "0.9" }
paste.workspace = true

[[test]]
name = "memberlist-quic"
path = "tests/main.rs"
required-features = ["test"]
