name: Cleanup Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: actions/github-script@v6
        with:
          script: |
            const threshold = new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)  // 1 day ago
            const runs = await github.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: 'completed'
            })
            for (const run of runs.data.workflow_runs) {
              if (new Date(run.created_at) < threshold) {
                await github.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id
                })
              }
            }
